core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('about_us', about_us, name='about_us'),
    path('payment', payment, name='payment'),

    path('terms_and_conditions', terms_and_conditions,
         name='terms_and_conditions'),
]

product/urls.py
from django.urls import path
from .views import *

app_name = 'product'

urlpatterns = [
    path('', products, name='products'),
    path('<int:id>/', overview, name='overview'),
    path('cart/', cart, name='cart'),

    path('create_order/', create_order, name='create_order'),

    path('add_to_cart/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/', remove_from_cart, name='remove_from_cart'),
]

shopzesta/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('user.urls')),
    path('products/', include('product.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('', index, name='index'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
]

core/models.py
from django.db import models


class Carousel(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='carousel')

    def __str__(self):
        return self.title

core/views.py
from django.shortcuts import render
from product.models import Product
from .models import *


def index(request):
    data = {
        'title': 'Home | Shopzesta',
        'products': Product.objects.all()[0:8],
        'carousel': Carousel.objects.all(),
    }
    return render(request, 'core/index.html', data)


def about_us(request):
    data = {
        'title': 'About us | Shopzesta',
    }
    return render(request, 'core/about_us.html', data)


def terms_and_conditions(request):
    data = {
        'title': 'Terms and conditions | Shopzesta',
    }
    return render(request, 'core/about_us.html', data)


def payment(request):
    data = {
        'title': 'Payment | Shopzesta',
    }
    return render(request, 'core/payment.html', data)

core/templates/footer.html
<!-- ========== FOOTER ========== -->
<footer class="border-top">
    <div class="container">


        <div class="row align-items-sm-center content-space-1">
            <div class="col-sm mb-4 mb-sm-0">
                <!-- Socials -->
                <ul class="list-inline mb-0">
                    <li class="list-inline-item">
                        <a class="btn btn-soft-secondary btn-xs btn-icon" href="#">
                            <i class="bi-facebook"></i>
                        </a>
                    </li>

                    <li class="list-inline-item">
                        <a class="btn btn-soft-secondary btn-xs btn-icon" href="#">
                            <i class="bi-google"></i>
                        </a>
                    </li>

                    <li class="list-inline-item">
                        <a class="btn btn-soft-secondary btn-xs btn-icon" href="#">
                            <i class="bi-twitter"></i>
                        </a>
                    </li>

                    <li class="list-inline-item">
                        <a class="btn btn-soft-secondary btn-xs btn-icon" href="#">
                            <i class="bi-github"></i>
                        </a>
                    </li>
                </ul>
                <!-- End Socials -->
            </div>

            <div class="col-sm-auto">
                <!-- List -->
                <ul class="list-inline list-separator">
                    <li class="list-inline-item">
                        <a class="link-sm link-secondary" href="#">Privacy &amp; policy</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="link-sm link-secondary" href="#">Terms &amp; conditions</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="link-sm link-secondary" href="#">Careers</a>
                    </li>
                </ul>
                <!-- End List -->
            </div>
        </div>
    </div>
</footer>
<!-- ========== END FOOTER ========== -->

core/templates/header.html
{% load static %}

<!-- ========== HEADER ========== -->
<header id="header" class="navbar navbar-expand-lg navbar-end navbar-light">


    <div class="container">
        <nav class="js-mega-menu navbar-nav-wrap">
            <!-- Default Logo -->
            <a class="navbar-brand" href="{% url 'core:index' %}" aria-label="Front">

                <h2 class="navbar-brand-logo text-primary">
                    <img class="w-50 img-fluid" src="{% static 'assets/logo100x100.jpg' %}" alt="Logo">
                </h2>
            </a>
            <!-- End Default Logo -->

            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-default">
                    <i class="bi-list"></i>
                </span>
                <span class="navbar-toggler-toggled">
                    <i class="bi-x"></i>
                </span>
            </button>
            <!-- End Toggler -->

            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'core:index' %}">Home</a>
                    </li>

                    <!-- Dropdown -->
                    {% if request.user.is_authenticated %}
                    <li class="hs-has-sub-menu nav-item">
                        <a id="listingsDropdown" class="hs-mega-menu-invoker nav-link dropdown-toggle " href="#"
                            role="button" data-bs-toggle="dropdown" aria-expanded="false">User</a>
                        <div class="hs-sub-menu dropdown-menu" aria-labelledby="listingsDropdown"
                            style="min-width: 14rem;">
                            <form action="{% url 'user:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item">Logout</button>
                            </form>

                            <!-- <a class="dropdown-item " href="../demo-shop/products-grid.html">Listing (Grid)</a> -->
                        </div>
                    </li>
                    {% endif %}
                    <!-- End Dropdown -->

                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'product:products' %}">Products</a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'core:about_us' %}">About us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'core:payment' %}">Payment</a>
                    </li>





                    <li class="nav-item">
                        <!-- Search -->
                        <!-- <button class="btn btn-ghost-secondary btn-sm btn-icon" type="button" data-bs-toggle="offcanvas"
                            data-bs-target="#offcanvasNavbarSearch" aria-controls="offcanvasNavbarSearch">
                            <i class="bi-search"></i>
                        </button> -->
                        <!-- End Search -->

                        <!-- Shopping Cart -->
                        <a href="{% url 'product:cart' %}" class="btn btn-ghost-secondary btn-sm btn-icon">
                            <i class="bi-basket"></i>
                        </a>
                        <!-- End Shopping Cart -->

                        {% if not request.user.is_authenticated %}
                        <a href="{% url 'user:login' %}" class="btn btn-primary btn-transition" type="button">Login</a>

                        <a href="{% url 'user:register' %}" class="btn btn-primary btn-transition"
                            type="button">Register</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
            <!-- End Collapse -->
        </nav>
    </div>
</header>

core/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="">

<head>

    <head>
        <!-- Required Meta Tags Always Come First -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Title -->
        <title>{{title}}</title>

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'assets/logo100x100.jpg' %}">

        <!-- Font -->
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">

        <!-- CSS Implementing Plugins -->
        <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-icons/font/bootstrap-icons.css' %}">
        <link rel="stylesheet" href="{% static 'assets/vendor/hs-mega-menu/dist/hs-mega-menu.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}">

        <!-- CSS Front Template -->
        <link rel="stylesheet" href="{% static 'assets/css/theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/my.css' %}">
    </head>
</head>

<body>

    {% include 'header.html' %}

    <main>
        {% block content %} {% endblock content %}
    </main>

    {% include 'footer.html' %}

</body>

<!-- JS Global Compulsory  -->
<script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>

<!-- JS Implementing Plugins -->
<script src="{% static 'assets/vendor/hs-mega-menu/dist/hs-mega-menu.min.js' %}"></script>
<script src="{% static 'assets/vendor/hs-show-animation/dist/hs-show-animation.min.js' %}"></script>
<script src="{% static 'assets/vendor/hs-go-to/dist/hs-go-to.min.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/countdown/countdown.js' %}"></script>



<!-- JS Front -->
<script src="{% static 'assets/js/theme.min.js' %}"></script>

<!-- JS Plugins Init. -->
<script>
    (function () {
        // INITIALIZATION OF MEGA MENU
        // =======================================================
        new HSMegaMenu('.js-mega-menu', {
            desktop: {
                position: 'left'
            }
        })


        // INITIALIZATION OF SHOW ANIMATIONS
        // =======================================================
        new HSShowAnimation('.js-animation-link')


        // INITIALIZATION OF BOOTSTRAP VALIDATION
        // =======================================================
        HSBsValidation.init('.js-validate', {
            onSubmit: data => {
                data.event.preventDefault()
                alert('Submited')
            }
        })


        // INITIALIZATION OF BOOTSTRAP DROPDOWN
        // =======================================================
        HSBsDropdown.init()


        // INITIALIZATION OF GO TO
        // =======================================================
        new HSGoTo('.js-go-to')


        // INITIALIZATION OF SWIPER
        // =======================================================
        var sliderThumbs = new Swiper('.js-swiper-shop-hero-thumbs', {
            watchSlidesVisibility: true,
            watchSlidesProgress: true,
            history: false,
            slidesPerView: 3,
            spaceBetween: 15,
            on: {
                beforeInit: (swiper) => {
                    const css = `.swiper-slide-thumb-active .swiper-thumb-progress .swiper-thumb-progress-path {
                  opacity: 1;
                  -webkit-animation: ${swiper.originalParams.autoplay.delay}ms linear 0ms forwards swiperThumbProgressDash;
                  animation: ${swiper.originalParams.autoplay.delay}ms linear 0ms forwards swiperThumbProgressDash;
              }`
                    style = document.createElement('style')
                    document.head.appendChild(style)
                    style.type = 'text/css'
                    style.appendChild(document.createTextNode(css));

                    swiper.el.querySelectorAll('.js-swiper-thumb-progress')
                        .forEach(slide => {
                            slide.insertAdjacentHTML('beforeend', '<span class="swiper-thumb-progress"><svg version="1.1" viewBox="0 0 160 160"><path class="swiper-thumb-progress-path" d="M 79.98452083651917 4.000001576345426 A 76 76 0 1 1 79.89443752470656 4.0000733121155605 Z"></path></svg></span>')
                        })
                },
            },
        });

        var swiper = new Swiper('.js-swiper-shop-classic-hero', {
            autoplay: true,
            loop: true,
            navigation: {
                nextEl: '.js-swiper-shop-classic-hero-button-next',
                prevEl: '.js-swiper-shop-classic-hero-button-prev',
            },
            thumbs: {
                swiper: sliderThumbs
            }
        });


        // INITIALIZATION OF COUNTDOWN
        // =======================================================
        const oneYearFromNow = new Date()

        document.querySelectorAll('.js-countdown').forEach(item => {
            const days = item.querySelector('.js-cd-days'),
                hours = item.querySelector('.js-cd-hours'),
                minutes = item.querySelector('.js-cd-minutes'),
                seconds = item.querySelector('.js-cd-seconds')

            countdown(oneYearFromNow.setFullYear(
                oneYearFromNow.getFullYear() + 1),
                ts => {
                    days.innerHTML = ts.days
                    hours.innerHTML = ts.hours
                    minutes.innerHTML = ts.minutes
                    seconds.innerHTML = ts.seconds
                },
                countdown.DAYS | countdown.HOURS | countdown.MINUTES | countdown.SECONDS
            )
        })
    })()
</script>


{% block js%} {% endblock js %}


</html>